In [2]:
import numpy as np
import pandas as pd
import scipy.stats as stats
import statsmodels.api as sm
import warnings
warnings.filterwarnings("ignore")
from PIL import ImageGrab
import matplotlib.pyplot as plt
import seaborn as sns


In [3]:
# We are going to conduct a Test of Independence using Chi-Square  test with Contingency table


In [4]:
# IMPORTING FILES

In [5]:
df=pd.read_csv('BuyerRatio.csv',index_col = 0)
df.head() 

East  West  North  South
Observed Values                          
Males              50   142    131     70
Females           435  1523   1356    750

In [6]:
table = [[50,142,131,70],
        [435,1523,1356,750]]

In [7]:
#Applying Chi-Square x2 contingency table to convert observed value into expected value


In [8]:
stat, p, dof, exp = stats.chi2_contingency(df) 
print(stat,"\n", p,"\n", dof,"\n", exp)


1.595945538661058 
 0.6603094907091882 
 3 
 [[  42.76531299  146.81287862  131.11756787   72.30424052]
 [ 442.23468701 1518.18712138 1355.88243213  747.69575948]]


In [9]:
stats.chi2_contingency(table) 

(1.595945538661058,
 0.6603094907091882,
 3,
 array([[  42.76531299,  146.81287862,  131.11756787,   72.30424052],
        [ 442.23468701, 1518.18712138, 1355.88243213,  747.69575948]]))

In [10]:
observed = np.array([50, 142, 131, 70, 435, 1523, 1356, 750])
expected = np.array([42.76531299,  146.81287862,  131.11756787, 72.30424052, 442.23468701, 1518.18712138, 1355.88243213, 747.69575948])

In [11]:
#Comparing Evidence with Hypothesis

In [12]:
statistics, p_value = stats.chisquare(observed, expected, ddof = 3)
print("Statistics = ",statistics,"\n",'P_Value = ', p_value)


Statistics =  1.5959455390914483 
 P_Value =  0.8095206646905712


In [13]:
#interpreting p-value
# As it is a one-tailed test
# alpha = 0.05

In [14]:
alpha = 0.05
print('Significnace=%.3f, p=%.3f' % (alpha, p_value))
if p_value <= alpha:
    print('We reject Null Hypothesis there is a significance difference between TAT of reports of the laboratories')
else:
    print('We accept Null hypothesis')


Significnace=0.050, p=0.810
We accept Null hypothesis


In [15]:
# Hence,We accept Null Hypothesis.Therefore,there is no association or dependency between male-female buyers rations and are similar across regions.